# -*- coding: utf-8 -*-
"""mlops_agent_refatorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JVOEyxnnU-anCm8WBQYIw-7x4P8y1f6
"""


from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
import requests
try:
    from evidently.presets.drift import DataDriftPreset
    from evidently.presets.dataset_stats import DataSummaryPreset as DataQualityPreset
    from evidently import Report
except ImportError:
    from evidently.metric_preset import DataDriftPreset, DataQualityPreset
    from evidently.report import Report
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

def data_process_tool(
    input_source: str | pd.DataFrame,
    reference_dataset_path: str,
) -> dict[str, pd.DataFrame | bool]:
    """Ingest new data and compare it against the reference dataset.

    Loads the reference dataset from disk, then identifies new records in the
    incoming source by row-level hashing. New records are appended to the
    reference to form a merged dataset returned alongside diagnostic flags.

    Args:
        input_source: Either a URL string pointing to a CSV file or a
            pre-loaded pandas DataFrame containing the incoming data.
        reference_dataset_path: Filesystem path to the reference CSV dataset
            used as the baseline for comparison.

    Returns:
        A dict with keys:
            - ``reference_data`` (pd.DataFrame): the original reference dataset.
            - ``new_data`` (pd.DataFrame): only the records not present in the
              reference dataset.
            - ``merged_data`` (pd.DataFrame): reference_data + new_data.
            - ``has_new_records`` (bool): True when at least one new record was
              found.

    Raises:
        ValueError: If ``input_source`` is neither a string nor a DataFrame.
        FileNotFoundError: If ``reference_dataset_path`` does not exist.
        requests.HTTPError: If fetching a CSV URL returns a non-2xx status.
    """
    logger.info("data_process_tool: loading reference dataset from '%s'", reference_dataset_path)

    reference_data = pd.read_csv(reference_dataset_path)
    logger.info("data_process_tool: reference dataset loaded with %d rows", len(reference_data))

    if isinstance(input_source, str):
        logger.info("data_process_tool: fetching new data from URL '%s'", input_source)
        response = requests.get(input_source, timeout=60)
        response.raise_for_status()
        from io import StringIO
        incoming_data = pd.read_csv(StringIO(response.text))
    elif isinstance(input_source, pd.DataFrame):
        incoming_data = input_source.copy()
    else:
        raise ValueError(
            f"input_source must be a URL string or pd.DataFrame, got {type(input_source)}"
        )
    logger.info("data_process_tool: incoming dataset has %d rows", len(incoming_data))

    def _row_hash(dataframe: pd.DataFrame) -> pd.Series:
        return dataframe.apply(
            lambda row: hashlib.md5(row.to_json().encode()).hexdigest(), axis=1
        )

    reference_hashes = set(_row_hash(reference_data))
    incoming_hashes = _row_hash(incoming_data)
    new_records_mask = ~incoming_hashes.isin(reference_hashes)
    new_data = incoming_data[new_records_mask].reset_index(drop=True)
    has_new_records = len(new_data) > 0

    logger.info(
        "data_process_tool: identified %d new record(s); has_new_records=%s",
        len(new_data),
        has_new_records,
    )

    merged_data = (
        pd.concat([reference_data, new_data], ignore_index=True)
        if has_new_records
        else reference_data.copy()
    )

    return {
        "reference_data": reference_data,
        "new_data": new_data,
        "merged_data": merged_data,
        "has_new_records": has_new_records,
    }


def data_drift_tool(
    reference_data: pd.DataFrame,
    new_data: pd.DataFrame,
    drift_share_threshold: float = 0.2,
) -> dict[str, bool | float | dict]:
    """Detect data drift between reference and new datasets using Evidently.

    Runs a DataDriftPreset and DataQualityPreset report, extracts per-feature
    drift information, and determines whether overall drift exceeds the
    configured threshold.

    Args:
        reference_data: The baseline dataset used as the drift reference.
        new_data: The incoming dataset to compare against the reference.
        drift_share_threshold: Fraction of drifted features above which overall
            drift is flagged. Defaults to 0.2.

    Returns:
        A dict with keys:
            - ``drift_detected`` (bool): True if drift_share >= threshold.
            - ``drift_report`` (dict): per-feature drift flags and scores.
            - ``drift_share`` (float): fraction of features that drifted.

    Raises:
        ValueError: If ``new_data`` is empty, making drift analysis impossible.
        RuntimeError: If Evidently report generation fails unexpectedly.
    """
    if new_data.empty:
        raise ValueError("new_data is empty; drift analysis requires at least one record.")

    logger.info(
        "data_drift_tool: running Evidently drift analysis on %d reference rows "
        "and %d new rows",
        len(reference_data),
        len(new_data),
    )

    try:
        evidently_report = Report(metrics=[DataDriftPreset()])
        snapshot = evidently_report.run(reference_data=reference_data, current_data=new_data)
        snapshot_dict = snapshot.dict()
    except Exception as exc:
        raise RuntimeError(f"Evidently report generation failed: {exc}") from exc

    drift_report: dict[str, Any] = {}
    drifted_feature_count = 0
    total_feature_count = 0

    drifted_columns_count = None
    drifted_columns_share = None

    for metric_entry in snapshot_dict.get("metrics", []):
        metric_name: str = metric_entry.get("metric_name", "")
        metric_value = metric_entry.get("value")

        if "DriftedColumnsCount" in metric_name and isinstance(metric_value, dict):
            drifted_columns_count = metric_value.get("count", 0)
            drifted_columns_share = metric_value.get("share", 0.0)

        elif "ValueDrift" in metric_name:
            config = metric_entry.get("config", {})
            feature_name = config.get("column", metric_name)
            threshold = float(config.get("threshold", 0.05))
            drift_score = float(metric_value) if metric_value is not None else None
            feature_drifted = (drift_score is not None) and (drift_score < threshold)

            drift_report[feature_name] = {
                "drift_detected": feature_drifted,
                "drift_score": drift_score,
            }
            total_feature_count += 1
            if feature_drifted:
                drifted_feature_count += 1
                logger.info(
                    "data_drift_tool: DRIFT detected on feature '%s' "
                    "(drift_score=%.4f, threshold=%.4f)",
                    feature_name,
                    drift_score,
                    threshold,
                )

    if drifted_columns_share is not None:
        drift_share = float(drifted_columns_share)
    elif total_feature_count > 0:
        drift_share = drifted_feature_count / total_feature_count
    else:
        drift_share = 0.0

    drift_detected = drift_share >= drift_share_threshold

    logger.info(
        "data_drift_tool: drift_share=%.4f, drift_share_threshold=%.4f, "
        "drift_detected=%s",
        drift_share,
        drift_share_threshold,
        drift_detected,
    )

    return {
        "drift_detected": drift_detected,
        "drift_report": drift_report,
        "drift_share": drift_share,
    }


def model_training_tool(
    input_data_train: pd.DataFrame,
    target_column: str,
    cv_folds: int = 5,
) -> dict[str, Any]:
    """Train and cross-validate multiple candidate classification models.

    Builds a preprocessing pipeline (imputation, scaling, one-hot encoding),
    then evaluates each candidate model via stratified k-fold cross-validation.
    Returns raw cross-validation results for downstream model selection.

    Args:
        input_data_train: The full training dataset including the target column.
        target_column: Name of the column to predict.
        cv_folds: Number of stratified folds for cross-validation. Defaults to 5.

    Returns:
        A dict with keys:
            - ``candidate_results`` (dict): maps each model name to its CV
              metrics (mean + std for f1_macro and roc_auc) and its fitted
              pipeline object.
            - ``feature_columns`` (list[str]): ordered list of feature column names.
            - ``label_encoder`` (LabelEncoder): fitted encoder for the target.
            - ``train_val_data`` (pd.DataFrame): 85% split used for training/val.
            - ``test_data`` (pd.DataFrame): held-out 15% test split.

    Raises:
        ValueError: If ``target_column`` is not found in ``input_data_train``.
        RuntimeError: If any candidate model fails to train.
    """
    if target_column not in input_data_train.columns:
        raise ValueError(
            f"target_column '{target_column}' not found in input_data_train. "
            f"Available columns: {list(input_data_train.columns)}"
        )

    logger.info(
        "model_training_tool: starting training on %d rows, target='%s', cv_folds=%d",
        len(input_data_train),
        target_column,
        cv_folds,
    )

    label_encoder = LabelEncoder()
    encoded_target = label_encoder.fit_transform(input_data_train[target_column])
    feature_data = input_data_train.drop(columns=[target_column])
    feature_columns = list(feature_data.columns)

    train_val_features, test_features, train_val_target, test_target = train_test_split(
        feature_data,
        encoded_target,
        test_size=0.15,
        random_state=42,
        stratify=encoded_target,
    )

    train_val_data = train_val_features.copy()
    train_val_data[target_column] = train_val_target
    test_data = test_features.copy()
    test_data[target_column] = test_target

    numerical_columns = feature_data.select_dtypes(include=["number"]).columns.tolist()
    categorical_columns = feature_data.select_dtypes(
        include=["object", "category"]
    ).columns.tolist()

    numerical_transformer = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )
    categorical_transformer = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ]
    )

    column_transformer = ColumnTransformer(
        transformers=[
            ("numerical", numerical_transformer, numerical_columns),
            ("categorical", categorical_transformer, categorical_columns),
        ],
        remainder="drop",
    )

    candidate_classifiers = {
        "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
        "GradientBoosting_XGB": XGBClassifier(
            n_estimators=100,
            random_state=42,
            eval_metric="logloss",
            use_label_encoder=False,
            verbosity=0,
        ),
        "LogisticRegression": LogisticRegression(max_iter=1000, random_state=42),
        "SupportVectorMachine": SVC(probability=True, random_state=42),
        "KNearestNeighbors": KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    }

    cross_val_splitter = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=42)
    scoring_metrics = {"f1_macro": "f1_macro", "roc_auc": "roc_auc_ovr"}

    candidate_results: dict[str, Any] = {}

    for model_name, classifier in candidate_classifiers.items():
        logger.info("model_training_tool: training candidate '%s'", model_name)
        try:
            full_pipeline = Pipeline(
                steps=[
                    ("preprocessor", column_transformer),
                    ("classifier", classifier),
                ]
            )
            cv_results = cross_validate(
                full_pipeline,
                train_val_features,
                train_val_target,
                cv=cross_val_splitter,
                scoring=scoring_metrics,
                return_estimator=True,
                n_jobs=-1,
            )
            mean_f1 = float(np.mean(cv_results["test_f1_macro"]))
            std_f1 = float(np.std(cv_results["test_f1_macro"]))
            mean_roc_auc = float(np.mean(cv_results["test_roc_auc"]))
            std_roc_auc = float(np.std(cv_results["test_roc_auc"]))

            best_fold_index = int(np.argmax(cv_results["test_f1_macro"]))
            best_fold_pipeline = cv_results["estimator"][best_fold_index]

            full_pipeline_fitted = Pipeline(
                steps=[
                    ("preprocessor", column_transformer),
                    ("classifier", classifier),
                ]
            )
            full_pipeline_fitted.fit(train_val_features, train_val_target)

            candidate_results[model_name] = {
                "mean_f1_macro": mean_f1,
                "std_f1_macro": std_f1,
                "mean_roc_auc": mean_roc_auc,
                "std_roc_auc": std_roc_auc,
                "fitted_pipeline": full_pipeline_fitted,
                "cv_raw_scores": {
                    "f1_macro": cv_results["test_f1_macro"].tolist(),
                    "roc_auc": cv_results["test_roc_auc"].tolist(),
                },
            }
            logger.info(
                "model_training_tool: '%s' — mean_f1_macro=%.4f (±%.4f), "
                "mean_roc_auc=%.4f (±%.4f)",
                model_name,
                mean_f1,
                std_f1,
                mean_roc_auc,
                std_roc_auc,
            )
        except Exception as exc:
            raise RuntimeError(
                f"Training candidate model '{model_name}' failed: {exc}"
            ) from exc

    return {
        "candidate_results": candidate_results,
        "feature_columns": feature_columns,
        "label_encoder": label_encoder,
        "train_val_data": train_val_data,
        "test_data": test_data,
        "target_column": target_column,
    }


def model_selection_tool(
    candidate_results: dict[str, Any],
    primary_metric: str = "f1_macro",
    tiebreaker_metric: str = "roc_auc",
) -> dict[str, Any]:
    """Select the best candidate model based on cross-validation metrics.

    Ranks all trained candidates by their mean cross-validated primary metric
    and uses the tiebreaker metric to resolve ties.

    Args:
        candidate_results: Mapping of model names to their CV metric dicts and
            fitted pipeline objects, as returned by ``model_training_tool``.
        primary_metric: Metric name (without ``mean_`` prefix) used for primary
            ranking. Defaults to ``"f1_macro"``.
        tiebreaker_metric: Metric name used to break primary-metric ties.
            Defaults to ``"roc_auc"``.

    Returns:
        A dict with keys:
            - ``best_estimator`` (Pipeline): the fitted sklearn Pipeline of the
              winning model.
            - ``selected_model_name`` (str): name of the winning model.
            - ``all_candidates_metrics`` (dict): summary metrics for every
              candidate evaluated.
            - ``best_f1_macro`` (float): primary metric score of the best model.
            - ``best_roc_auc`` (float): tiebreaker metric score of the best model.

    Raises:
        ValueError: If ``candidate_results`` is empty.
    """
    if not candidate_results:
        raise ValueError("candidate_results is empty; no models to select from.")

    primary_metric_key = f"mean_{primary_metric}"
    tiebreaker_metric_key = f"mean_{tiebreaker_metric}"

    all_candidates_metrics: dict[str, dict[str, float]] = {}
    for model_name, result in candidate_results.items():
        all_candidates_metrics[model_name] = {
            "mean_f1_macro": result["mean_f1_macro"],
            "std_f1_macro": result["std_f1_macro"],
            "mean_roc_auc": result["mean_roc_auc"],
            "std_roc_auc": result["std_roc_auc"],
        }

    sorted_candidates = sorted(
        candidate_results.items(),
        key=lambda item: (
            item[1][primary_metric_key],
            item[1][tiebreaker_metric_key],
        ),
        reverse=True,
    )

    selected_model_name, best_candidate_data = sorted_candidates[0]
    best_estimator = best_candidate_data["fitted_pipeline"]

    logger.info(
        "model_selection_tool: selected '%s' — %s=%.4f, %s=%.4f",
        selected_model_name,
        primary_metric_key,
        best_candidate_data[primary_metric_key],
        tiebreaker_metric_key,
        best_candidate_data[tiebreaker_metric_key],
    )

    return {
        "best_estimator": best_estimator,
        "selected_model_name": selected_model_name,
        "all_candidates_metrics": all_candidates_metrics,
        "best_f1_macro": best_candidate_data[primary_metric_key],
        "best_roc_auc": best_candidate_data[tiebreaker_metric_key],
    }


def model_evaluation_tool(
    trained_pipeline: Pipeline,
    input_data_test: pd.DataFrame,
    target_test: pd.Series,
    current_model_metrics_path: str | None,
    improvement_threshold: float = 0.005,
) -> dict[str, Any]:
    """Evaluate a newly trained model and compare it to the production model.

    Computes a full suite of classification metrics on the held-out test set and
    loads the current production model's metrics from disk for comparison. The
    new model is considered better if its F1-macro exceeds the production model's
    F1-macro by at least ``improvement_threshold``.

    Args:
        trained_pipeline: A fitted sklearn Pipeline to evaluate.
        input_data_test: Feature matrix for the held-out test split.
        target_test: Ground-truth labels for the test split.
        current_model_metrics_path: Path to a JSON file containing the current
            production model's metrics. Pass ``None`` if no production model
            exists yet.
        improvement_threshold: Minimum F1-macro improvement required to consider
            the new model better than the production model. Defaults to 0.005.

    Returns:
        A dict with keys:
            - ``new_model_metrics`` (dict[str, float]): computed test metrics.
            - ``current_model_metrics`` (dict[str, float] | None): metrics loaded
              from disk, or None if no production model exists.
            - ``is_better`` (bool): True if the new model exceeds the threshold.

    Raises:
        FileNotFoundError: If ``current_model_metrics_path`` is provided but the
            file does not exist.
        json.JSONDecodeError: If the metrics file cannot be parsed.
    """
    logger.info(
        "model_evaluation_tool: evaluating new model on %d test samples",
        len(input_data_test),
    )

    predicted_labels = trained_pipeline.predict(input_data_test)
    predicted_probabilities = trained_pipeline.predict_proba(input_data_test)

    number_of_classes = len(np.unique(target_test))
    roc_auc_averaging = "ovr" if number_of_classes > 2 else "raise"

    if number_of_classes == 2:
        roc_auc_value = float(
            roc_auc_score(target_test, predicted_probabilities[:, 1])
        )
    else:
        roc_auc_value = float(
            roc_auc_score(
                target_test,
                predicted_probabilities,
                multi_class="ovr",
                average="macro",
            )
        )

    new_model_metrics: dict[str, float] = {
        "accuracy": float(accuracy_score(target_test, predicted_labels)),
        "f1_macro": float(
            f1_score(target_test, predicted_labels, average="macro", zero_division=0)
        ),
        "precision_macro": float(
            precision_score(
                target_test, predicted_labels, average="macro", zero_division=0
            )
        ),
        "recall_macro": float(
            recall_score(
                target_test, predicted_labels, average="macro", zero_division=0
            )
        ),
        "roc_auc": roc_auc_value,
    }

    logger.info(
        "model_evaluation_tool: new model — accuracy=%.4f, f1_macro=%.4f, "
        "precision_macro=%.4f, recall_macro=%.4f, roc_auc=%.4f",
        new_model_metrics["accuracy"],
        new_model_metrics["f1_macro"],
        new_model_metrics["precision_macro"],
        new_model_metrics["recall_macro"],
        new_model_metrics["roc_auc"],
    )

    current_model_metrics: dict[str, float] | None = None
    if current_model_metrics_path is not None:
        metrics_path = Path(current_model_metrics_path)
        if not metrics_path.exists():
            raise FileNotFoundError(
                f"Current model metrics file not found: {current_model_metrics_path}"
            )
        try:
            with metrics_path.open("r", encoding="utf-8") as metrics_file:
                current_model_metrics = json.load(metrics_file)
            logger.info(
                "model_evaluation_tool: production model f1_macro=%.4f",
                current_model_metrics.get("f1_macro", float("nan")),
            )
        except json.JSONDecodeError as exc:
            raise json.JSONDecodeError(
                f"Failed to parse metrics file at '{current_model_metrics_path}': {exc.msg}",
                exc.doc,
                exc.pos,
            ) from exc

    if current_model_metrics is None:
        is_better = True
        logger.info(
            "model_evaluation_tool: no production model found; new model is accepted by default"
        )
    else:
        production_f1 = current_model_metrics.get("f1_macro", 0.0)
        new_f1 = new_model_metrics["f1_macro"]
        is_better = (new_f1 - production_f1) >= improvement_threshold
        logger.info(
            "model_evaluation_tool: new_f1=%.4f, production_f1=%.4f, "
            "improvement=%.4f, threshold=%.4f, is_better=%s",
            new_f1,
            production_f1,
            new_f1 - production_f1,
            improvement_threshold,
            is_better,
        )

    return {
        "new_model_metrics": new_model_metrics,
        "current_model_metrics": current_model_metrics,
        "is_better": is_better,
    }


def deploy_application_tool(
    trained_pipeline: Pipeline,
    new_model_metrics: dict[str, float],
    model_artifact_path: str,
    metrics_artifact_path: str,
    github_owner: str,
    github_repo: str,
    workflow_id: str,
    target_branch: str,
    github_token: str,
) -> dict[str, bool | int | str]:
    """Persist the trained model and trigger a GitHub Actions deployment.

    Saves the sklearn Pipeline artifact to disk with joblib and writes updated
    metrics to a JSON file. Then dispatches a GitHub Actions workflow via the
    workflow dispatch API endpoint.

    Args:
        trained_pipeline: The fitted sklearn Pipeline to persist.
        new_model_metrics: Dictionary of evaluation metrics for the new model.
        model_artifact_path: Filesystem path where the model joblib file will
            be saved.
        metrics_artifact_path: Filesystem path where the metrics JSON file will
            be saved.
        github_owner: GitHub username or organization that owns the repository.
        github_repo: Repository name where the Actions workflow is defined.
        workflow_id: Filename or numeric ID of the GitHub Actions workflow to
            dispatch (e.g. ``"retrain.yml"``).
        target_branch: Git ref (branch name) passed as ``ref`` in the dispatch
            payload.
        github_token: Personal access token with ``repo`` and ``actions:write``
            scopes for authenticating the GitHub API request.

    Returns:
        A dict with keys:
            - ``deployment_triggered`` (bool): True when HTTP response is 2xx.
            - ``http_status_code`` (int): raw HTTP status from the API.
            - ``response_body`` (str): raw response text from the API.

    Raises:
        OSError: If saving the model artifact or metrics file fails.
        requests.exceptions.RequestException: If the GitHub API request fails
            due to a network-level error.
        RuntimeError: If the GitHub API returns a non-2xx status code.
    """
    logger.info(
        "deploy_application_tool: saving model artifact to '%s'", model_artifact_path
    )
    try:
        Path(model_artifact_path).parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(trained_pipeline, model_artifact_path)
        logger.info("deploy_application_tool: model artifact saved successfully")
    except OSError as exc:
        raise OSError(
            f"Failed to save model artifact to '{model_artifact_path}': {exc}"
        ) from exc

    logger.info(
        "deploy_application_tool: saving metrics to '%s'", metrics_artifact_path
    )
    try:
        Path(metrics_artifact_path).parent.mkdir(parents=True, exist_ok=True)
        with open(metrics_artifact_path, "w", encoding="utf-8") as metrics_file:
            json.dump(new_model_metrics, metrics_file, indent=2)
        logger.info("deploy_application_tool: metrics file saved successfully")
    except OSError as exc:
        raise OSError(
            f"Failed to save metrics to '{metrics_artifact_path}': {exc}"
        ) from exc

    model_version = new_model_metrics.get("f1_macro", 0.0)
    dispatch_url = (
        f"https://api.github.com/repos/{github_owner}/{github_repo}"
        f"/actions/workflows/{workflow_id}/dispatches"
    )
    dispatch_payload = {
        "ref": target_branch,
        "inputs": {
            "model_version": str(model_version),
            "artifact_path": model_artifact_path,
            "f1_score": str(new_model_metrics.get("f1_macro", "")),
        },
    }
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json",
    }

    logger.info(
        "deploy_application_tool: dispatching workflow '%s' on branch '%s' "
        "for repo '%s/%s'",
        workflow_id,
        target_branch,
        github_owner,
        github_repo,
    )

    try:
        api_response = requests.post(
            dispatch_url,
            headers=headers,
            json=dispatch_payload,
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        raise requests.exceptions.RequestException(
            f"GitHub API request failed (network error): {exc}"
        ) from exc

    http_status_code = api_response.status_code
    response_body = api_response.text
    deployment_triggered = 200 <= http_status_code < 300

    if deployment_triggered:
        logger.info(
            "deploy_application_tool: GitHub Actions dispatch succeeded "
            "(status=%d)",
            http_status_code,
        )
    else:
        raise RuntimeError(
            f"GitHub Actions dispatch failed with HTTP {http_status_code}: {response_body}"
        )

    return {
        "deployment_triggered": deployment_triggered,
        "http_status_code": http_status_code,
        "response_body": response_body,
    }


# ---------------------------------------------------------------------------
# Agent State
# ---------------------------------------------------------------------------

from typing import TypedDict


class AgentState(TypedDict, total=False):
    """Carries all inter-step state through the LangGraph StateGraph.

    Attributes:
        input_source: Incoming data source — URL string or DataFrame.
        reference_dataset_path: Path to the on-disk reference dataset CSV.
        target_column: Name of the column to predict.
        current_model_metrics_path: Path to the production model metrics JSON.
        model_artifact_path: Destination path for the saved model joblib file.
        metrics_artifact_path: Destination path for the saved metrics JSON.
        github_owner: GitHub repo owner for the Actions dispatch.
        github_repo: GitHub repo name for the Actions dispatch.
        workflow_id: GitHub Actions workflow filename or ID.
        target_branch: Git branch for the workflow dispatch.
        github_token: GitHub personal access token.
        reference_data: Reference DataFrame after data_process_tool.
        new_data: New-records-only DataFrame after data_process_tool.
        merged_data: Merged (reference + new) DataFrame.
        has_new_records: Whether any new records were found.
        drift_detected: Whether Evidently detected significant drift.
        drift_report: Per-feature drift summary dict.
        drift_share: Share of drifted features.
        candidate_results: Raw CV results from model_training_tool.
        feature_columns: Ordered list of feature column names.
        label_encoder: Fitted LabelEncoder for the target.
        train_val_data: 85% split used for training.
        test_data: Held-out 15% test split.
        best_estimator: The selected best fitted Pipeline.
        selected_model_name: Name of the winning candidate model.
        all_candidates_metrics: Summary metrics for all evaluated candidates.
        new_model_metrics: Test-set metrics for the new model.
        current_model_metrics: Production model metrics loaded from disk.
        is_better: Whether the new model clears the improvement threshold.
        deployment_triggered: Whether the GitHub workflow was dispatched.
        http_status_code: HTTP status code from the GitHub API.
        halt_reason: Human-readable reason when the agent halts early.
    """

    input_source: str | pd.DataFrame
    reference_dataset_path: str
    target_column: str
    current_model_metrics_path: str | None
    model_artifact_path: str
    metrics_artifact_path: str
    github_owner: str
    github_repo: str
    workflow_id: str
    target_branch: str
    github_token: str

    reference_data: pd.DataFrame
    new_data: pd.DataFrame
    merged_data: pd.DataFrame
    has_new_records: bool

    drift_detected: bool
    drift_report: dict
    drift_share: float

    candidate_results: dict
    feature_columns: list
    label_encoder: LabelEncoder
    train_val_data: pd.DataFrame
    test_data: pd.DataFrame

    best_estimator: Pipeline
    selected_model_name: str
    all_candidates_metrics: dict

    new_model_metrics: dict
    current_model_metrics: dict | None
    is_better: bool

    deployment_triggered: bool
    http_status_code: int
    halt_reason: str


# ---------------------------------------------------------------------------
# LangGraph node wrappers
# ---------------------------------------------------------------------------

from langgraph.graph import StateGraph, END


def node_data_process(state: AgentState) -> AgentState:
    """LangGraph node: run data ingestion and comparison.

    Args:
        state: The current agent state carrying ``input_source`` and
            ``reference_dataset_path``.

    Returns:
        Updated state with ``reference_data``, ``new_data``, ``merged_data``,
        and ``has_new_records`` populated.
    """
    result = data_process_tool(
        input_source=state["input_source"],
        reference_dataset_path=state["reference_dataset_path"],
    )
    return {**state, **result}


def node_data_drift(state: AgentState) -> AgentState:
    """LangGraph node: run Evidently drift detection.

    Args:
        state: The current agent state with ``reference_data`` and ``new_data``.

    Returns:
        Updated state with ``drift_detected``, ``drift_report``, and
        ``drift_share`` populated.
    """
    result = data_drift_tool(
        reference_data=state["reference_data"],
        new_data=state["new_data"],
    )
    return {**state, **result}


def node_model_training(state: AgentState) -> AgentState:
    """LangGraph node: train candidate models via cross-validation.

    Args:
        state: The current agent state with ``merged_data`` and
            ``target_column``.

    Returns:
        Updated state with ``candidate_results``, ``feature_columns``,
        ``label_encoder``, ``train_val_data``, and ``test_data`` populated.
    """
    result = model_training_tool(
        input_data_train=state["merged_data"],
        target_column=state["target_column"],
    )
    return {**state, **result}


def node_model_selection(state: AgentState) -> AgentState:
    """LangGraph node: select the best candidate model.

    Args:
        state: The current agent state with ``candidate_results``.

    Returns:
        Updated state with ``best_estimator``, ``selected_model_name``, and
        ``all_candidates_metrics`` populated.
    """
    result = model_selection_tool(candidate_results=state["candidate_results"])
    return {**state, **result}


def node_model_evaluation(state: AgentState) -> AgentState:
    """LangGraph node: evaluate the best model on the test split.

    Args:
        state: The current agent state with ``best_estimator``, ``test_data``,
            ``target_column``, and ``current_model_metrics_path``.

    Returns:
        Updated state with ``new_model_metrics``, ``current_model_metrics``,
        and ``is_better`` populated.
    """
    test_features = state["test_data"].drop(columns=[state["target_column"]])
    test_target = state["test_data"][state["target_column"]]
    result = model_evaluation_tool(
        trained_pipeline=state["best_estimator"],
        input_data_test=test_features,
        target_test=test_target,
        current_model_metrics_path=state.get("current_model_metrics_path"),
    )
    return {**state, **result}


def node_deploy(state: AgentState) -> AgentState:
    """LangGraph node: persist the model artifact and trigger GitHub Actions.

    Args:
        state: The current agent state with all deployment configuration and
            the fitted ``best_estimator``.

    Returns:
        Updated state with ``deployment_triggered`` and ``http_status_code``
        populated.
    """
    result = deploy_application_tool(
        trained_pipeline=state["best_estimator"],
        new_model_metrics=state["new_model_metrics"],
        model_artifact_path=state["model_artifact_path"],
        metrics_artifact_path=state["metrics_artifact_path"],
        github_owner=state["github_owner"],
        github_repo=state["github_repo"],
        workflow_id=state["workflow_id"],
        target_branch=state["target_branch"],
        github_token=state["github_token"],
    )
    logger.info("Deployment triggered successfully.")
    return {**state, **result}


def node_halt_no_change(state: AgentState) -> AgentState:
    """LangGraph node: halt because no drift and no new records were detected.

    Args:
        state: The current agent state.

    Returns:
        Updated state with ``halt_reason`` set.
    """
    reason = "No drift detected, no new data. Skipping retraining."
    logger.warning(reason)
    return {**state, "halt_reason": reason}


def node_halt_underperforms(state: AgentState) -> AgentState:
    """LangGraph node: halt because the new model does not beat production.

    Args:
        state: The current agent state with ``new_model_metrics`` and
            ``current_model_metrics``.

    Returns:
        Updated state with ``halt_reason`` set.
    """
    new_f1 = state.get("new_model_metrics", {}).get("f1_macro", float("nan"))
    prod_f1 = (
        state.get("current_model_metrics") or {}
    ).get("f1_macro", float("nan"))
    reason = (
        f"New model underperforms. Skipping deployment. "
        f"new_f1_macro={new_f1:.4f}, production_f1_macro={prod_f1:.4f}"
    )
    logger.warning(reason)
    return {**state, "halt_reason": reason}


# ---------------------------------------------------------------------------
# Conditional edge routing functions
# ---------------------------------------------------------------------------


def route_after_data_process(state: AgentState) -> str:
    """Route after data_process_tool: drift check or immediate halt.

    Args:
        state: Current agent state with ``has_new_records``.

    Returns:
        Node name to transition to next.
    """
    if state.get("has_new_records"):
        return "data_drift"
    return "halt_no_change"


def route_after_data_drift(state: AgentState) -> str:
    """Route after data_drift_tool: train or halt.

    Args:
        state: Current agent state with ``drift_detected`` and
            ``has_new_records``.

    Returns:
        Node name to transition to next.
    """
    if state.get("drift_detected") or state.get("has_new_records"):
        return "model_training"
    return "halt_no_change"


def route_after_evaluation(state: AgentState) -> str:
    """Route after model_evaluation_tool: deploy or halt.

    Args:
        state: Current agent state with ``is_better``.

    Returns:
        Node name to transition to next.
    """
    if state.get("is_better"):
        return "deploy"
    return "halt_underperforms"


# ---------------------------------------------------------------------------
# MLOps Training Agent
# ---------------------------------------------------------------------------


class MLOpsTrainingAgent:
    """Production-grade MLOps agent for automated model retraining and deployment.

    Orchestrates the complete model lifecycle: data ingestion, drift detection,
    candidate training, model selection, evaluation against the current
    production model, and conditional deployment via GitHub Actions.

    The internal reasoning loop is implemented as a LangGraph ``StateGraph``
    with conditional edges that mirror the decision rules in the specification.

    Args:
        reference_dataset_path: Filesystem path to the reference dataset CSV
            used as the drift baseline and training anchor.
        target_column: Name of the column to predict in the dataset.
        current_model_metrics_path: Path to the current production model's
            metrics JSON file. Pass ``None`` when no production model exists.
        model_artifact_path: Destination path for the saved model artifact.
        metrics_artifact_path: Destination path for the saved metrics JSON.
        github_owner: GitHub username or organization that owns the repository.
        github_repo: Repository name where the Actions workflow lives.
        workflow_id: Filename or numeric ID of the GitHub Actions workflow
            (e.g. ``"retrain.yml"``).
        target_branch: Git branch ref to pass in the workflow dispatch payload.
        github_token: Personal access token with ``repo`` and
            ``actions:write`` scopes.

    Example:
        >>> agent = MLOpsTrainingAgent(
        ...     reference_dataset_path="data/reference.csv",
        ...     target_column="label",
        ...     current_model_metrics_path="artifacts/metrics.json",
        ...     model_artifact_path="artifacts/model.joblib",
        ...     metrics_artifact_path="artifacts/metrics.json",
        ...     github_owner="acme",
        ...     github_repo="ml-service",
        ...     workflow_id="retrain.yml",
        ...     target_branch="main",
        ...     github_token="ghp_...",
        ... )
        >>> final_state = agent.run("https://example.com/new_data.csv")
    """

    def __init__(
        self,
        reference_dataset_path: str,
        target_column: str,
        current_model_metrics_path: str | None,
        model_artifact_path: str,
        metrics_artifact_path: str,
        github_owner: str,
        github_repo: str,
        workflow_id: str,
        target_branch: str,
        github_token: str,
    ) -> None:
        self._config: dict[str, Any] = {
            "reference_dataset_path": reference_dataset_path,
            "target_column": target_column,
            "current_model_metrics_path": current_model_metrics_path,
            "model_artifact_path": model_artifact_path,
            "metrics_artifact_path": metrics_artifact_path,
            "github_owner": github_owner,
            "github_repo": github_repo,
            "workflow_id": workflow_id,
            "target_branch": target_branch,
            "github_token": github_token,
        }
        self._graph = self._build_graph()

    def _build_graph(self) -> Any:
        """Construct and compile the LangGraph StateGraph.

        Returns:
            A compiled LangGraph runnable graph.
        """
        workflow = StateGraph(AgentState)

        workflow.add_node("data_process", node_data_process)
        workflow.add_node("data_drift", node_data_drift)
        workflow.add_node("model_training", node_model_training)
        workflow.add_node("model_selection", node_model_selection)
        workflow.add_node("model_evaluation", node_model_evaluation)
        workflow.add_node("deploy", node_deploy)
        workflow.add_node("halt_no_change", node_halt_no_change)
        workflow.add_node("halt_underperforms", node_halt_underperforms)

        workflow.set_entry_point("data_process")

        workflow.add_conditional_edges(
            "data_process",
            route_after_data_process,
            {
                "data_drift": "data_drift",
                "halt_no_change": "halt_no_change",
            },
        )
        workflow.add_conditional_edges(
            "data_drift",
            route_after_data_drift,
            {
                "model_training": "model_training",
                "halt_no_change": "halt_no_change",
            },
        )

        workflow.add_edge("model_training", "model_selection")
        workflow.add_edge("model_selection", "model_evaluation")

        workflow.add_conditional_edges(
            "model_evaluation",
            route_after_evaluation,
            {
                "deploy": "deploy",
                "halt_underperforms": "halt_underperforms",
            },
        )

        workflow.add_edge("deploy", END)
        workflow.add_edge("halt_no_change", END)
        workflow.add_edge("halt_underperforms", END)

        return workflow.compile()

    def run(self, input_source: str | pd.DataFrame) -> AgentState:
        """Execute the full MLOps pipeline for the given input data.

        Args:
            input_source: Either a URL pointing to a CSV file or a pre-loaded
                pandas DataFrame containing the new data to process.

        Returns:
            The final ``AgentState`` after the graph has reached a terminal
            node. Inspect ``state["halt_reason"]`` for early-exit details or
            ``state["deployment_triggered"]`` to confirm a successful deploy.

        Raises:
            Any exception propagated from the underlying tool functions.
        """
        initial_state: AgentState = {**self._config, "input_source": input_source}
        logger.info(
            "MLOpsTrainingAgent.run: starting pipeline for input_source=%s",
            input_source if isinstance(input_source, str) else f"<DataFrame shape={input_source.shape}>",
        )
        final_state: AgentState = self._graph.invoke(initial_state)
        return final_state

agent = MLOpsTrainingAgent(
    reference_dataset_path="https://raw.githubusercontent.com/renansantosmendes/mlops-datasets/refs/heads/main/data_20230720_04-51-43.csv", # seu CSV de referência
    target_column="fetal_health", # nome da coluna alvo
    current_model_metrics_path=None, # None se não tem modelo em produção ainda
    model_artifact_path="artifacts/model.joblib",
    metrics_artifact_path="artifacts/metrics.json",
    github_owner="seu-usuario",
    github_repo="seu-repositorio",
    workflow_id="retrain.yml",
    target_branch="main",
    github_token="ghp_...", # seu token do GitHub
)

final_state = agent.run("https://raw.githubusercontent.com/renansantosmendes/mlops-datasets/refs/heads/main/data_20230725_09-15-46.csv")

